apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-rmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: conv-rmq
          image: rabbitmq:3.8.34-management
          ports: 
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: AMQP_USER
                  name: conv-rmq-secret
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: AMQP_PASSWORD
                  name: conv-rmq-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "200m"
          volumeMounts:
            - name: conv-rmq-volume
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: conv-rmq-volume
          persistentVolumeClaim:
            claimName: conv-rmq-pvc