apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rmq.name }}-secret
type: Opaque
stringData:
  # AMQP_EXCHANGE: "test"
  # AMQP_USER: "demo"
  # AMQP_PASSWORD: "demo"
  # AMQP_HOSTNAME: "conv-rmq-clusterip"
  # AMQP_QUEUE: "converter"
  AMQP_EXCHANGE: {{ .Values.queue.exchange | quote }}
  AMQP_USER: {{ .Values.queue.user | quote }}
  AMQP_PASSWORD: {{ .Values.queue.password | quote }}
  AMQP_HOSTNAME: {{ .Values.queue.hostname | quote }}
  AMQP_QUEUE: {{ .Values.queue.queue | quote }}