apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      components: service
  template:
    metadata:
      name: conv-service
      labels:
        components: service
    spec:
      containers:
        - name: conv-service
          image:  antonlarichev/conv-service:1.0
          ports: 
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: conv-rmq-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-rmq-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_HOSTNAME
              value: conv-rmq-clusterip
            - name: AMQP_EXCHANGE
              value: test
            - name: AMQP_QUEUE
              value: converter