apiVersion: v1
kind: Secret
metadata:
  name: conv-rmq-secret
type: Opaque
stringData:
  AMQP_EXCHANGE: "test"
  AMQP_USER: "demo"
  AMQP_PASSWORD: "demo"
  AMQP_HOSTNAME: "conv-rmq-clusterip"
  AMQP_QUEUE: "converter"